---
 
apiVersion: v1
kind: Namespace
metadata:
  name: hello
 
---
 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: hello
  annotations:
    buildNumber: "1.0"
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
      annotations:
        buildNumber: "1.0"
    spec:
      containers:
        - name: hello-world
          image: vleong99/hello:v1.1
          readinessProbe:
            httpGet:
              path: "/ping"
              port: 8000
            initialDelaySeconds: 2
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          env:
            - name: APPLICATION_VERSION
              value: "1.0"
---
 
 
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: hello
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
---